apiVersion: batch/v1
kind: Job
metadata:
  name: etl-job
spec:
  template:
    spec:
      containers:
        - name: etl
          image: my-etl-job:latest
          volumeMounts:
            - name: sales-data
              mountPath: /data
      volumes:
        - name: sales-data
          hostPath:
            path: /host-data
            type: Directory
      restartPolicy: Never
  backoffLimit: 3
